fix(jwt): provide algorithm when verifying signature and issuer
navikt/mock-oauth2-server pull request #353
Opened 2022-10-12 15:39 UTC by antoineauger

I just discovered this project yesterday and setup/used it with success today. 
This is the perfect fit for one of our internal project, so a huge thanks 🙏🏻 

This MR fixes the errors returned by some endpoints when using a non-default  `algorithm`, for instance `RS384`:

```json
{
  "tokenProvider" : {
    "keyProvider" : {
      "algorithm" : "RS384"
    }
  }
}
```

Before this MR, if the token generated with algorithms was different than `RS256`, the following error was returned by the `/userinfo` and `introspect` endpoints :

```json
{
  "error_description": "signed jwt rejected: another algorithm expected, or no matching key(s) found",
  "error": "invalid_token"
}
```

:hammer_and_wrench: with :heart: by [Siemens](https://opensource.siemens.com/)

2022-10-12 18:46 UTC, ybelMekk commented
Hi and thank you for opening this PR.

Looking forward too.. 👀

2022-10-14 15:19 UTC, antoineauger commented
@ybelMekk This is ready for review 🙏🏻 

I also fixed some minor typos, reformat files and clean some unused imports 😉

2022-10-14 19:17 UTC, ybelMekk requested changes
Apart from the printlns, this PR LGTM 🥇

2022-10-14 19:17 UTC, ybelMekk commented on src/test/kotlin/no/nav/security/mock/oauth2/introspect/IntrospectTest.kt
> +        println("token: " + token.jwtClaimsSet.toJSONObject())
should rhe prinltn still be here? 😄

2022-10-14 19:17 UTC, ybelMekk commented on src/test/kotlin/no/nav/security/mock/oauth2/introspect/IntrospectTest.kt
> +        println("token: " + token.jwtClaimsSet.toJSONObject())
same her.

2022-10-17 07:57 UTC, antoineauger commented on src/test/kotlin/no/nav/security/mock/oauth2/introspect/IntrospectTest.kt
> +        println("token: " + token.jwtClaimsSet.toJSONObject())
Haha thanks for spotting that 🙇🏻 

Removed in e9cd5699dc2c0f1d0f51b2031842a64382c22739

2022-10-17 07:57 UTC, antoineauger commented on src/test/kotlin/no/nav/security/mock/oauth2/introspect/IntrospectTest.kt
> +        println("token: " + token.jwtClaimsSet.toJSONObject())
Removed in e9cd5699dc2c0f1d0f51b2031842a64382c22739

2022-10-17 07:58 UTC, antoineauger commented
> Apart from the printlns, this PR LGTM 1st_place_medal

@ybelMekk I removed the unwanted `println`s 😁 

Thanks for the review 🏓

2022-10-17 10:10 UTC, ybelMekk commented
@tommytroen you have the final say 😄

2022-10-17 10:20 UTC, tommytroen commented
LGTM 🏆

2022-10-17 10:21 UTC, merged