Add ability to specify JWT type in header
navikt/mock-oauth2-server pull request #53
Opened 2021-08-12 13:06 UTC by fgstewart

In some cases token issuing servers issue tokens with `typ` set to something other than "JWT".

In order to mock those we need to be able to override the default `typ` in the json config.

2021-08-16 12:03 UTC, ybelMekk requested changes
The PR is stable.

2021-08-16 12:53 UTC, fgstewart commented on src/main/kotlin/no/nav/security/mock/oauth2/token/OAuth2TokenProvider.kt
> +    private fun JWTClaimsSet.sign(issuerId: String, type: String?): SignedJWT {
Thanks for the feedback, I've removed the nullable.

2021-08-16 13:03 UTC, ybelMekk approved these changes

2021-08-17 10:31 UTC, ybelMekk requested changes

2021-08-17 10:31 UTC, ybelMekk commented on src/main/kotlin/no/nav/security/mock/oauth2/token/OAuth2TokenCallback.kt
> +    fun type(tokenRequest: TokenRequest): String
Had a discussion about the naming with a team mate. Have a little comment about this, `type`, do not describe what we really setting in the interface here. Could be `typeHeader` or `mediaType` or something more describing.. changes goes for methods to.

2021-08-17 11:06 UTC, fgstewart commented on src/main/kotlin/no/nav/security/mock/oauth2/token/OAuth2TokenCallback.kt
> +    fun type(tokenRequest: TokenRequest): String
Thanks for the feedback, it makes sense.I've renamed to `typeHeader`.

2021-08-17 11:29 UTC, ybelMekk approved these changes

2021-08-17 11:41 UTC, tommytroen requested changes
lgtm. `headerType` should probably be renamed to `typeHeader` to avoid confusion with "which type of header is this?"

2021-08-17 12:09 UTC, fgstewart commented
> lgtm. `headerType` should probably be renamed to `typeHeader` to avoid confusion with "which type of header is this?"

Done, thanks.

2021-08-17 12:33 UTC, tommytroen approved these changes

2021-08-17 13:07 UTC, merged